### ISSUE TITLE
read-amplification-select.partition-pruning-generated-columns: duplicating in val definition q1 

### ISSUE THREAD

**Issue by dhamerkhalil** [AmadeusITGroup/spark-perf-hikes#13]
should be renamed.

command-4242071650476893:42: error: q1 is already defined as value q1
val q1 = spark.sql(s"SELECT * FROM delta.`${delta}` WHERE datetime_pp > '2022-01'")

**Comment by mauriciojost** [comment]
Thanks for spotting it! Fixing it right now.
